name = "PDArp";
tooltip = "PDArp - By Ivan Kishchenko & Istar Eldritch";
overview = "Adds PDA to the game. Allows players to communicate with each other in personal chats.";
author = "Ivan Kishchenko / Istar Eldritch";
version = "0.2";
picture = "PDArp/data/PDArp_logo_m.paa";
logoSmall = "PDArp/data/PDArp_logo_ss.paa";
logo = "PDArp/data/PDArp_logo_s.paa";
logoOver = "PDArp/data/PDArp_logo_s.paa";